/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/collections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Customers and what they owe */
        get: operations["listCollections"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/collections/{collection_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One customer */
        get: operations["getCollection"];
        /** Edit a pending customer */
        put: operations["updateCollection"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/collections/{collection_id}/mark-paid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** The employer confirms the money was received (manual, no verification) */
        post: operations["markCollectionPaid"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/collections/{collection_id}/mark-unpaid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Undo a Mark as Paid click (a plain status correction, nothing else changes) */
        post: operations["markCollectionUnpaid"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/collections/{collection_id}/payment-page": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create this customer's payment-page link (the same link is returned if it exists) */
        post: operations["generatePaymentPage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Four simple numbers and the latest customers */
        get: operations["getDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/imports/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Save the reviewed rows as customers (all or nothing) */
        post: operations["confirmImport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/imports/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Read an .xlsx/.csv file and show the rows */
        post: operations["previewImport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/imports/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Re-check rows after the employer edits them */
        post: operations["validateImportRows"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current employer (derived from the verified session) */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/pay/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** What the customer sees */
        get: operations["getPublicPaymentPage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/pay/{token}/qr": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The company's general QR image, exactly as uploaded in Settings */
        get: operations["getPublicPaymentQr"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/payment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Payment settings (own employer only) */
        get: operations["getPaymentSettings"];
        /** Save payment settings (payment details need a recent password confirmation) */
        put: operations["updatePaymentSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/payment/qr": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The employer's own QR image (authenticated; never public) */
        get: operations["getPaymentQr"];
        /** Upload or replace the QR image (PNG/JPG, max 2 MB, at least 300×300) */
        put: operations["uploadPaymentQr"];
        post?: never;
        /** Remove the QR image (turn the QR method off first) */
        delete: operations["deletePaymentQr"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness probe (checks the database) */
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BankDetails */
        BankDetails: {
            /** Account Name */
            account_name: string | null;
            /** Account Number */
            account_number: string;
            /** Bank Name */
            bank_name: string | null;
            /** Ifsc */
            ifsc: string | null;
        };
        /** Body_previewImport */
        Body_previewImport: {
            /** File */
            file: string;
        };
        /** Body_uploadPaymentQr */
        Body_uploadPaymentQr: {
            /** File */
            file: string;
        };
        /** CollectionDetail */
        CollectionDetail: {
            /** Amount Due */
            amount_due: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Customer Name */
            customer_name: string;
            /** Due Date */
            due_date: string | null;
            /** Has Payment Page */
            has_payment_page: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Payment Token */
            payment_token: string | null;
            /** Phone */
            phone: string | null;
            /** Reference */
            reference: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "PENDING" | "PAID";
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** CollectionEdit */
        CollectionEdit: {
            /** Amount Due */
            amount_due?: string | null;
            /** Customer Name */
            customer_name?: string | null;
            /** Due Date */
            due_date?: string | null;
            /** Phone */
            phone?: string | null;
            /** Reference */
            reference?: string | null;
        };
        /** CollectionList */
        CollectionList: {
            /** Items */
            items: components["schemas"]["CollectionRow"][];
            /** Total */
            total: number;
        };
        /** CollectionRow */
        CollectionRow: {
            /** Amount Due */
            amount_due: string;
            /** Customer Name */
            customer_name: string;
            /** Due Date */
            due_date: string | null;
            /** Has Payment Page */
            has_payment_page: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Phone */
            phone: string | null;
            /** Reference */
            reference: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "PENDING" | "PAID";
        };
        /** ConfirmIn */
        ConfirmIn: {
            /**
             * Filename
             * @default
             */
            filename: string;
            /** Rows */
            rows: components["schemas"]["RowIn"][];
        };
        /** ConfirmOut */
        ConfirmOut: {
            /** Imported */
            imported: number;
        };
        /** DashboardOut */
        DashboardOut: {
            /** Customers */
            customers: number;
            /** Paid Amount */
            paid_amount: string;
            /** Pending Customers */
            pending_customers: number;
            /** Recent */
            recent: components["schemas"]["RecentRow"][];
            /** Total Outstanding */
            total_outstanding: string;
        };
        /** EmployerOut */
        EmployerOut: {
            /** Email */
            email: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
        };
        /** FieldError */
        FieldError: {
            /** Field */
            field: string;
            /** Message */
            message: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
        };
        /** MeResponse */
        MeResponse: {
            employer: components["schemas"]["EmployerOut"];
        };
        /** PaymentSettingsIn */
        PaymentSettingsIn: {
            /** Account Name */
            account_name?: string | null;
            /** Account Number */
            account_number?: string | null;
            /**
             * Bank Enabled
             * @default false
             */
            bank_enabled: boolean;
            /** Bank Name */
            bank_name?: string | null;
            /** Display Name */
            display_name: string;
            /** Ifsc */
            ifsc?: string | null;
            /**
             * Qr Enabled
             * @default false
             */
            qr_enabled: boolean;
            /**
             * Upi Enabled
             * @default false
             */
            upi_enabled: boolean;
            /** Upi Id */
            upi_id?: string | null;
            /** Upi Number */
            upi_number?: string | null;
            /**
             * Upi Number Enabled
             * @default false
             */
            upi_number_enabled: boolean;
        };
        /** PaymentSettingsOut */
        PaymentSettingsOut: {
            /** Account Name */
            account_name: string | null;
            /** Account Number */
            account_number: string | null;
            /** Bank Enabled */
            bank_enabled: boolean;
            /** Bank Name */
            bank_name: string | null;
            /** Display Name */
            display_name: string | null;
            /** Has Qr */
            has_qr: boolean;
            /** Ifsc */
            ifsc: string | null;
            /** Qr Enabled */
            qr_enabled: boolean;
            /** Recent Changes */
            recent_changes: components["schemas"]["SettingChange"][];
            /** Updated At */
            updated_at: string | null;
            /** Upi Enabled */
            upi_enabled: boolean;
            /** Upi Id */
            upi_id: string | null;
            /** Upi Number */
            upi_number: string | null;
            /** Upi Number Enabled */
            upi_number_enabled: boolean;
        };
        /** PreviewOut */
        PreviewOut: {
            /** Filename */
            filename: string;
            /** Invalid */
            invalid: number;
            /** Rows */
            rows: components["schemas"]["RowOut"][];
            /** Total */
            total: number;
            /** Valid */
            valid: number;
        };
        /** PublicPage */
        PublicPage: {
            /** Amount Due */
            amount_due?: string | null;
            bank?: components["schemas"]["BankDetails"] | null;
            /** Company Name */
            company_name: string;
            /** Customer Name */
            customer_name: string;
            /**
             * Has Qr
             * @default false
             */
            has_qr: boolean;
            /** Reference */
            reference?: string | null;
            /**
             * State
             * @enum {string}
             */
            state: "PENDING" | "PAID";
            /** Upi Id */
            upi_id?: string | null;
            /** Upi Number */
            upi_number?: string | null;
        };
        /** RecentRow */
        RecentRow: {
            /** Amount Due */
            amount_due: string;
            /** Customer Name */
            customer_name: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "PENDING" | "PAID";
        };
        /**
         * RowIn
         * @description A row after the employer reviewed/edited it. The server re-validates everything.
         */
        RowIn: {
            /** Amount Due */
            amount_due?: string | null;
            /** Customer Name */
            customer_name?: string | null;
            /** Due Date */
            due_date?: string | null;
            /** Phone */
            phone?: string | null;
            /** Reference */
            reference?: string | null;
            /**
             * Row Number
             * @default 0
             */
            row_number: number;
        };
        /** RowOut */
        RowOut: {
            /** Amount Due */
            amount_due: string;
            /** Customer Name */
            customer_name: string;
            /** Due Date */
            due_date: string | null;
            /** Errors */
            errors: components["schemas"]["FieldError"][];
            /** Phone */
            phone: string | null;
            /** Reference */
            reference: string | null;
            /** Row Number */
            row_number: number;
        };
        /** RowsIn */
        RowsIn: {
            /** Rows */
            rows: components["schemas"]["RowIn"][];
        };
        /** SettingChange */
        SettingChange: {
            /** Actor */
            actor: string;
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Fields */
            fields: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listCollections: {
        parameters: {
            query?: {
                status?: ("PENDING" | "PAID") | null;
                q?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getCollection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collection_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    updateCollection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collection_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CollectionEdit"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    markCollectionPaid: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collection_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    markCollectionUnpaid: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collection_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generatePaymentPage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collection_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getDashboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardOut"];
                };
            };
        };
    };
    confirmImport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfirmOut"];
                };
            };
            /** @description Some rows still have errors */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    previewImport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_previewImport"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validateImportRows: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RowsIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RowOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    getPublicPaymentPage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getPublicPaymentQr: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/png": unknown;
                };
            };
            /** @description No QR */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getPaymentSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentSettingsOut"];
                };
            };
        };
    };
    updatePaymentSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaymentSettingsIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentSettingsOut"];
                };
            };
            /** @description Recent password confirmation required (reauth_required) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getPaymentQr: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/png": unknown;
                };
            };
            /** @description No QR image */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    uploadPaymentQr: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_uploadPaymentQr"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentSettingsOut"];
                };
            };
            /** @description Recent password confirmation required (reauth_required) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deletePaymentQr: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentSettingsOut"];
                };
            };
            /** @description Recent password confirmation required (reauth_required) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
